# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/unlimit/KPQClean

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/unlimit/KPQClean

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unlimit/KPQClean/CMakeFiles /home/unlimit/KPQClean//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unlimit/KPQClean/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f common/CMakeFiles/common.dir/build.make common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named haetae2_fips202

# Build rule for target.
haetae2_fips202: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2_fips202
.PHONY : haetae2_fips202

# fast build rule for target.
haetae2_fips202/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/CMakeFiles/haetae2_fips202.dir/build.make crypto_sign/HAETAE2/CMakeFiles/haetae2_fips202.dir/build
.PHONY : haetae2_fips202/fast

#=============================================================================
# Target rules for targets named haetae2_RNG

# Build rule for target.
haetae2_RNG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2_RNG
.PHONY : haetae2_RNG

# fast build rule for target.
haetae2_RNG/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/CMakeFiles/haetae2_RNG.dir/build.make crypto_sign/HAETAE2/CMakeFiles/haetae2_RNG.dir/build
.PHONY : haetae2_RNG/fast

#=============================================================================
# Target rules for targets named haetae2

# Build rule for target.
haetae2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2
.PHONY : haetae2

# fast build rule for target.
haetae2/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/CMakeFiles/haetae2.dir/build.make crypto_sign/HAETAE2/CMakeFiles/haetae2.dir/build
.PHONY : haetae2/fast

#=============================================================================
# Target rules for targets named haetae2-main

# Build rule for target.
haetae2-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2-main
.PHONY : haetae2-main

# fast build rule for target.
haetae2-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/test/CMakeFiles/haetae2-main.dir/build.make crypto_sign/HAETAE2/test/CMakeFiles/haetae2-main.dir/build
.PHONY : haetae2-main/fast

#=============================================================================
# Target rules for targets named haetae2-kat-sign

# Build rule for target.
haetae2-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2-kat-sign
.PHONY : haetae2-kat-sign

# fast build rule for target.
haetae2-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/kat/CMakeFiles/haetae2-kat-sign.dir/build.make crypto_sign/HAETAE2/kat/CMakeFiles/haetae2-kat-sign.dir/build
.PHONY : haetae2-kat-sign/fast

#=============================================================================
# Target rules for targets named haetae2-kat-sign-main

# Build rule for target.
haetae2-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2-kat-sign-main
.PHONY : haetae2-kat-sign-main

# fast build rule for target.
haetae2-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/kat/CMakeFiles/haetae2-kat-sign-main.dir/build.make crypto_sign/HAETAE2/kat/CMakeFiles/haetae2-kat-sign-main.dir/build
.PHONY : haetae2-kat-sign-main/fast

#=============================================================================
# Target rules for targets named haetae2-benchmark

# Build rule for target.
haetae2-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2-benchmark
.PHONY : haetae2-benchmark

# fast build rule for target.
haetae2-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/benchmark/CMakeFiles/haetae2-benchmark.dir/build.make crypto_sign/HAETAE2/benchmark/CMakeFiles/haetae2-benchmark.dir/build
.PHONY : haetae2-benchmark/fast

#=============================================================================
# Target rules for targets named haetae2-meta

# Build rule for target.
haetae2-meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2-meta
.PHONY : haetae2-meta

# fast build rule for target.
haetae2-meta/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/metamorphic/CMakeFiles/haetae2-meta.dir/build.make crypto_sign/HAETAE2/metamorphic/CMakeFiles/haetae2-meta.dir/build
.PHONY : haetae2-meta/fast

#=============================================================================
# Target rules for targets named haetae2-meta-main

# Build rule for target.
haetae2-meta-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae2-meta-main
.PHONY : haetae2-meta-main

# fast build rule for target.
haetae2-meta-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE2/metamorphic/CMakeFiles/haetae2-meta-main.dir/build.make crypto_sign/HAETAE2/metamorphic/CMakeFiles/haetae2-meta-main.dir/build
.PHONY : haetae2-meta-main/fast

#=============================================================================
# Target rules for targets named haetae3_fips202

# Build rule for target.
haetae3_fips202: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3_fips202
.PHONY : haetae3_fips202

# fast build rule for target.
haetae3_fips202/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/CMakeFiles/haetae3_fips202.dir/build.make crypto_sign/HAETAE3/CMakeFiles/haetae3_fips202.dir/build
.PHONY : haetae3_fips202/fast

#=============================================================================
# Target rules for targets named haetae3_RNG

# Build rule for target.
haetae3_RNG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3_RNG
.PHONY : haetae3_RNG

# fast build rule for target.
haetae3_RNG/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/CMakeFiles/haetae3_RNG.dir/build.make crypto_sign/HAETAE3/CMakeFiles/haetae3_RNG.dir/build
.PHONY : haetae3_RNG/fast

#=============================================================================
# Target rules for targets named haetae3

# Build rule for target.
haetae3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3
.PHONY : haetae3

# fast build rule for target.
haetae3/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/CMakeFiles/haetae3.dir/build.make crypto_sign/HAETAE3/CMakeFiles/haetae3.dir/build
.PHONY : haetae3/fast

#=============================================================================
# Target rules for targets named haetae3-main

# Build rule for target.
haetae3-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3-main
.PHONY : haetae3-main

# fast build rule for target.
haetae3-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/test/CMakeFiles/haetae3-main.dir/build.make crypto_sign/HAETAE3/test/CMakeFiles/haetae3-main.dir/build
.PHONY : haetae3-main/fast

#=============================================================================
# Target rules for targets named haetae3-kat-sign

# Build rule for target.
haetae3-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3-kat-sign
.PHONY : haetae3-kat-sign

# fast build rule for target.
haetae3-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/kat/CMakeFiles/haetae3-kat-sign.dir/build.make crypto_sign/HAETAE3/kat/CMakeFiles/haetae3-kat-sign.dir/build
.PHONY : haetae3-kat-sign/fast

#=============================================================================
# Target rules for targets named haetae3-kat-sign-main

# Build rule for target.
haetae3-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3-kat-sign-main
.PHONY : haetae3-kat-sign-main

# fast build rule for target.
haetae3-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/kat/CMakeFiles/haetae3-kat-sign-main.dir/build.make crypto_sign/HAETAE3/kat/CMakeFiles/haetae3-kat-sign-main.dir/build
.PHONY : haetae3-kat-sign-main/fast

#=============================================================================
# Target rules for targets named haetae3-benchmark

# Build rule for target.
haetae3-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3-benchmark
.PHONY : haetae3-benchmark

# fast build rule for target.
haetae3-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/benchmark/CMakeFiles/haetae3-benchmark.dir/build.make crypto_sign/HAETAE3/benchmark/CMakeFiles/haetae3-benchmark.dir/build
.PHONY : haetae3-benchmark/fast

#=============================================================================
# Target rules for targets named haetae3-meta

# Build rule for target.
haetae3-meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3-meta
.PHONY : haetae3-meta

# fast build rule for target.
haetae3-meta/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/metamorphic/CMakeFiles/haetae3-meta.dir/build.make crypto_sign/HAETAE3/metamorphic/CMakeFiles/haetae3-meta.dir/build
.PHONY : haetae3-meta/fast

#=============================================================================
# Target rules for targets named haetae3-meta-main

# Build rule for target.
haetae3-meta-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae3-meta-main
.PHONY : haetae3-meta-main

# fast build rule for target.
haetae3-meta-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE3/metamorphic/CMakeFiles/haetae3-meta-main.dir/build.make crypto_sign/HAETAE3/metamorphic/CMakeFiles/haetae3-meta-main.dir/build
.PHONY : haetae3-meta-main/fast

#=============================================================================
# Target rules for targets named haetae5_fips202

# Build rule for target.
haetae5_fips202: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5_fips202
.PHONY : haetae5_fips202

# fast build rule for target.
haetae5_fips202/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/CMakeFiles/haetae5_fips202.dir/build.make crypto_sign/HAETAE5/CMakeFiles/haetae5_fips202.dir/build
.PHONY : haetae5_fips202/fast

#=============================================================================
# Target rules for targets named haetae5_RNG

# Build rule for target.
haetae5_RNG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5_RNG
.PHONY : haetae5_RNG

# fast build rule for target.
haetae5_RNG/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/CMakeFiles/haetae5_RNG.dir/build.make crypto_sign/HAETAE5/CMakeFiles/haetae5_RNG.dir/build
.PHONY : haetae5_RNG/fast

#=============================================================================
# Target rules for targets named haetae5

# Build rule for target.
haetae5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5
.PHONY : haetae5

# fast build rule for target.
haetae5/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/CMakeFiles/haetae5.dir/build.make crypto_sign/HAETAE5/CMakeFiles/haetae5.dir/build
.PHONY : haetae5/fast

#=============================================================================
# Target rules for targets named haetae5-main

# Build rule for target.
haetae5-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5-main
.PHONY : haetae5-main

# fast build rule for target.
haetae5-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/test/CMakeFiles/haetae5-main.dir/build.make crypto_sign/HAETAE5/test/CMakeFiles/haetae5-main.dir/build
.PHONY : haetae5-main/fast

#=============================================================================
# Target rules for targets named haetae5-kat-sign

# Build rule for target.
haetae5-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5-kat-sign
.PHONY : haetae5-kat-sign

# fast build rule for target.
haetae5-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/kat/CMakeFiles/haetae5-kat-sign.dir/build.make crypto_sign/HAETAE5/kat/CMakeFiles/haetae5-kat-sign.dir/build
.PHONY : haetae5-kat-sign/fast

#=============================================================================
# Target rules for targets named haetae5-kat-sign-main

# Build rule for target.
haetae5-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5-kat-sign-main
.PHONY : haetae5-kat-sign-main

# fast build rule for target.
haetae5-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/kat/CMakeFiles/haetae5-kat-sign-main.dir/build.make crypto_sign/HAETAE5/kat/CMakeFiles/haetae5-kat-sign-main.dir/build
.PHONY : haetae5-kat-sign-main/fast

#=============================================================================
# Target rules for targets named haetae5-benchmark

# Build rule for target.
haetae5-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5-benchmark
.PHONY : haetae5-benchmark

# fast build rule for target.
haetae5-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/benchmark/CMakeFiles/haetae5-benchmark.dir/build.make crypto_sign/HAETAE5/benchmark/CMakeFiles/haetae5-benchmark.dir/build
.PHONY : haetae5-benchmark/fast

#=============================================================================
# Target rules for targets named haetae5-meta

# Build rule for target.
haetae5-meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5-meta
.PHONY : haetae5-meta

# fast build rule for target.
haetae5-meta/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/metamorphic/CMakeFiles/haetae5-meta.dir/build.make crypto_sign/HAETAE5/metamorphic/CMakeFiles/haetae5-meta.dir/build
.PHONY : haetae5-meta/fast

#=============================================================================
# Target rules for targets named haetae5-meta-main

# Build rule for target.
haetae5-meta-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 haetae5-meta-main
.PHONY : haetae5-meta-main

# fast build rule for target.
haetae5-meta-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/HAETAE5/metamorphic/CMakeFiles/haetae5-meta-main.dir/build.make crypto_sign/HAETAE5/metamorphic/CMakeFiles/haetae5-meta-main.dir/build
.PHONY : haetae5-meta-main/fast

#=============================================================================
# Target rules for targets named nccsign2_fips202

# Build rule for target.
nccsign2_fips202: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign2_fips202
.PHONY : nccsign2_fips202

# fast build rule for target.
nccsign2_fips202/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/CMakeFiles/nccsign2_fips202.dir/build.make crypto_sign/NCCSign2-ori/CMakeFiles/nccsign2_fips202.dir/build
.PHONY : nccsign2_fips202/fast

#=============================================================================
# Target rules for targets named nccsign2_aes256ctr

# Build rule for target.
nccsign2_aes256ctr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign2_aes256ctr
.PHONY : nccsign2_aes256ctr

# fast build rule for target.
nccsign2_aes256ctr/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/CMakeFiles/nccsign2_aes256ctr.dir/build.make crypto_sign/NCCSign2-ori/CMakeFiles/nccsign2_aes256ctr.dir/build
.PHONY : nccsign2_aes256ctr/fast

#=============================================================================
# Target rules for targets named nccsign-ori2

# Build rule for target.
nccsign-ori2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2
.PHONY : nccsign-ori2

# fast build rule for target.
nccsign-ori2/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/CMakeFiles/nccsign-ori2.dir/build.make crypto_sign/NCCSign2-ori/CMakeFiles/nccsign-ori2.dir/build
.PHONY : nccsign-ori2/fast

#=============================================================================
# Target rules for targets named nccsign-ori2aes

# Build rule for target.
nccsign-ori2aes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2aes
.PHONY : nccsign-ori2aes

# fast build rule for target.
nccsign-ori2aes/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/CMakeFiles/nccsign-ori2aes.dir/build.make crypto_sign/NCCSign2-ori/CMakeFiles/nccsign-ori2aes.dir/build
.PHONY : nccsign-ori2aes/fast

#=============================================================================
# Target rules for targets named nccsign-ori2-main

# Build rule for target.
nccsign-ori2-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2-main
.PHONY : nccsign-ori2-main

# fast build rule for target.
nccsign-ori2-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/test/CMakeFiles/nccsign-ori2-main.dir/build.make crypto_sign/NCCSign2-ori/test/CMakeFiles/nccsign-ori2-main.dir/build
.PHONY : nccsign-ori2-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori2aes-main

# Build rule for target.
nccsign-ori2aes-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2aes-main
.PHONY : nccsign-ori2aes-main

# fast build rule for target.
nccsign-ori2aes-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/test/CMakeFiles/nccsign-ori2aes-main.dir/build.make crypto_sign/NCCSign2-ori/test/CMakeFiles/nccsign-ori2aes-main.dir/build
.PHONY : nccsign-ori2aes-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori2-kat-sign

# Build rule for target.
nccsign-ori2-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2-kat-sign
.PHONY : nccsign-ori2-kat-sign

# fast build rule for target.
nccsign-ori2-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/kat/CMakeFiles/nccsign-ori2-kat-sign.dir/build.make crypto_sign/NCCSign2-ori/kat/CMakeFiles/nccsign-ori2-kat-sign.dir/build
.PHONY : nccsign-ori2-kat-sign/fast

#=============================================================================
# Target rules for targets named nccsign-ori2-kat-sign-main

# Build rule for target.
nccsign-ori2-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2-kat-sign-main
.PHONY : nccsign-ori2-kat-sign-main

# fast build rule for target.
nccsign-ori2-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/kat/CMakeFiles/nccsign-ori2-kat-sign-main.dir/build.make crypto_sign/NCCSign2-ori/kat/CMakeFiles/nccsign-ori2-kat-sign-main.dir/build
.PHONY : nccsign-ori2-kat-sign-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori2aes-kat-sign

# Build rule for target.
nccsign-ori2aes-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2aes-kat-sign
.PHONY : nccsign-ori2aes-kat-sign

# fast build rule for target.
nccsign-ori2aes-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/kat/CMakeFiles/nccsign-ori2aes-kat-sign.dir/build.make crypto_sign/NCCSign2-ori/kat/CMakeFiles/nccsign-ori2aes-kat-sign.dir/build
.PHONY : nccsign-ori2aes-kat-sign/fast

#=============================================================================
# Target rules for targets named nccsign-ori2aes-kat-sign-main

# Build rule for target.
nccsign-ori2aes-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2aes-kat-sign-main
.PHONY : nccsign-ori2aes-kat-sign-main

# fast build rule for target.
nccsign-ori2aes-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/kat/CMakeFiles/nccsign-ori2aes-kat-sign-main.dir/build.make crypto_sign/NCCSign2-ori/kat/CMakeFiles/nccsign-ori2aes-kat-sign-main.dir/build
.PHONY : nccsign-ori2aes-kat-sign-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori2-benchmark

# Build rule for target.
nccsign-ori2-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2-benchmark
.PHONY : nccsign-ori2-benchmark

# fast build rule for target.
nccsign-ori2-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/benchmark/CMakeFiles/nccsign-ori2-benchmark.dir/build.make crypto_sign/NCCSign2-ori/benchmark/CMakeFiles/nccsign-ori2-benchmark.dir/build
.PHONY : nccsign-ori2-benchmark/fast

#=============================================================================
# Target rules for targets named nccsign-ori2aes-benchmark

# Build rule for target.
nccsign-ori2aes-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori2aes-benchmark
.PHONY : nccsign-ori2aes-benchmark

# fast build rule for target.
nccsign-ori2aes-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign2-ori/benchmark/CMakeFiles/nccsign-ori2aes-benchmark.dir/build.make crypto_sign/NCCSign2-ori/benchmark/CMakeFiles/nccsign-ori2aes-benchmark.dir/build
.PHONY : nccsign-ori2aes-benchmark/fast

#=============================================================================
# Target rules for targets named nccsign3_fips202

# Build rule for target.
nccsign3_fips202: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign3_fips202
.PHONY : nccsign3_fips202

# fast build rule for target.
nccsign3_fips202/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/CMakeFiles/nccsign3_fips202.dir/build.make crypto_sign/NCCSign3-ori/CMakeFiles/nccsign3_fips202.dir/build
.PHONY : nccsign3_fips202/fast

#=============================================================================
# Target rules for targets named nccsign3_aes256ctr

# Build rule for target.
nccsign3_aes256ctr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign3_aes256ctr
.PHONY : nccsign3_aes256ctr

# fast build rule for target.
nccsign3_aes256ctr/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/CMakeFiles/nccsign3_aes256ctr.dir/build.make crypto_sign/NCCSign3-ori/CMakeFiles/nccsign3_aes256ctr.dir/build
.PHONY : nccsign3_aes256ctr/fast

#=============================================================================
# Target rules for targets named nccsign-ori3

# Build rule for target.
nccsign-ori3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3
.PHONY : nccsign-ori3

# fast build rule for target.
nccsign-ori3/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/CMakeFiles/nccsign-ori3.dir/build.make crypto_sign/NCCSign3-ori/CMakeFiles/nccsign-ori3.dir/build
.PHONY : nccsign-ori3/fast

#=============================================================================
# Target rules for targets named nccsign-ori3aes

# Build rule for target.
nccsign-ori3aes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3aes
.PHONY : nccsign-ori3aes

# fast build rule for target.
nccsign-ori3aes/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/CMakeFiles/nccsign-ori3aes.dir/build.make crypto_sign/NCCSign3-ori/CMakeFiles/nccsign-ori3aes.dir/build
.PHONY : nccsign-ori3aes/fast

#=============================================================================
# Target rules for targets named nccsign-ori3-main

# Build rule for target.
nccsign-ori3-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3-main
.PHONY : nccsign-ori3-main

# fast build rule for target.
nccsign-ori3-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/test/CMakeFiles/nccsign-ori3-main.dir/build.make crypto_sign/NCCSign3-ori/test/CMakeFiles/nccsign-ori3-main.dir/build
.PHONY : nccsign-ori3-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori3aes-main

# Build rule for target.
nccsign-ori3aes-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3aes-main
.PHONY : nccsign-ori3aes-main

# fast build rule for target.
nccsign-ori3aes-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/test/CMakeFiles/nccsign-ori3aes-main.dir/build.make crypto_sign/NCCSign3-ori/test/CMakeFiles/nccsign-ori3aes-main.dir/build
.PHONY : nccsign-ori3aes-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori3-kat-sign

# Build rule for target.
nccsign-ori3-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3-kat-sign
.PHONY : nccsign-ori3-kat-sign

# fast build rule for target.
nccsign-ori3-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/kat/CMakeFiles/nccsign-ori3-kat-sign.dir/build.make crypto_sign/NCCSign3-ori/kat/CMakeFiles/nccsign-ori3-kat-sign.dir/build
.PHONY : nccsign-ori3-kat-sign/fast

#=============================================================================
# Target rules for targets named nccsign-ori3-kat-sign-main

# Build rule for target.
nccsign-ori3-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3-kat-sign-main
.PHONY : nccsign-ori3-kat-sign-main

# fast build rule for target.
nccsign-ori3-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/kat/CMakeFiles/nccsign-ori3-kat-sign-main.dir/build.make crypto_sign/NCCSign3-ori/kat/CMakeFiles/nccsign-ori3-kat-sign-main.dir/build
.PHONY : nccsign-ori3-kat-sign-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori3aes-kat-sign

# Build rule for target.
nccsign-ori3aes-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3aes-kat-sign
.PHONY : nccsign-ori3aes-kat-sign

# fast build rule for target.
nccsign-ori3aes-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/kat/CMakeFiles/nccsign-ori3aes-kat-sign.dir/build.make crypto_sign/NCCSign3-ori/kat/CMakeFiles/nccsign-ori3aes-kat-sign.dir/build
.PHONY : nccsign-ori3aes-kat-sign/fast

#=============================================================================
# Target rules for targets named nccsign-ori3aes-kat-sign-main

# Build rule for target.
nccsign-ori3aes-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3aes-kat-sign-main
.PHONY : nccsign-ori3aes-kat-sign-main

# fast build rule for target.
nccsign-ori3aes-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/kat/CMakeFiles/nccsign-ori3aes-kat-sign-main.dir/build.make crypto_sign/NCCSign3-ori/kat/CMakeFiles/nccsign-ori3aes-kat-sign-main.dir/build
.PHONY : nccsign-ori3aes-kat-sign-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori3-benchmark

# Build rule for target.
nccsign-ori3-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3-benchmark
.PHONY : nccsign-ori3-benchmark

# fast build rule for target.
nccsign-ori3-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/benchmark/CMakeFiles/nccsign-ori3-benchmark.dir/build.make crypto_sign/NCCSign3-ori/benchmark/CMakeFiles/nccsign-ori3-benchmark.dir/build
.PHONY : nccsign-ori3-benchmark/fast

#=============================================================================
# Target rules for targets named nccsign-ori3aes-benchmark

# Build rule for target.
nccsign-ori3aes-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori3aes-benchmark
.PHONY : nccsign-ori3aes-benchmark

# fast build rule for target.
nccsign-ori3aes-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign3-ori/benchmark/CMakeFiles/nccsign-ori3aes-benchmark.dir/build.make crypto_sign/NCCSign3-ori/benchmark/CMakeFiles/nccsign-ori3aes-benchmark.dir/build
.PHONY : nccsign-ori3aes-benchmark/fast

#=============================================================================
# Target rules for targets named nccsign5_fips202

# Build rule for target.
nccsign5_fips202: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign5_fips202
.PHONY : nccsign5_fips202

# fast build rule for target.
nccsign5_fips202/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/CMakeFiles/nccsign5_fips202.dir/build.make crypto_sign/NCCSign5-ori/CMakeFiles/nccsign5_fips202.dir/build
.PHONY : nccsign5_fips202/fast

#=============================================================================
# Target rules for targets named nccsign5_aes256ctr

# Build rule for target.
nccsign5_aes256ctr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign5_aes256ctr
.PHONY : nccsign5_aes256ctr

# fast build rule for target.
nccsign5_aes256ctr/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/CMakeFiles/nccsign5_aes256ctr.dir/build.make crypto_sign/NCCSign5-ori/CMakeFiles/nccsign5_aes256ctr.dir/build
.PHONY : nccsign5_aes256ctr/fast

#=============================================================================
# Target rules for targets named nccsign-ori5

# Build rule for target.
nccsign-ori5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5
.PHONY : nccsign-ori5

# fast build rule for target.
nccsign-ori5/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/CMakeFiles/nccsign-ori5.dir/build.make crypto_sign/NCCSign5-ori/CMakeFiles/nccsign-ori5.dir/build
.PHONY : nccsign-ori5/fast

#=============================================================================
# Target rules for targets named nccsign-ori5aes

# Build rule for target.
nccsign-ori5aes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5aes
.PHONY : nccsign-ori5aes

# fast build rule for target.
nccsign-ori5aes/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/CMakeFiles/nccsign-ori5aes.dir/build.make crypto_sign/NCCSign5-ori/CMakeFiles/nccsign-ori5aes.dir/build
.PHONY : nccsign-ori5aes/fast

#=============================================================================
# Target rules for targets named nccsign-ori5-main

# Build rule for target.
nccsign-ori5-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5-main
.PHONY : nccsign-ori5-main

# fast build rule for target.
nccsign-ori5-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/test/CMakeFiles/nccsign-ori5-main.dir/build.make crypto_sign/NCCSign5-ori/test/CMakeFiles/nccsign-ori5-main.dir/build
.PHONY : nccsign-ori5-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori5aes-main

# Build rule for target.
nccsign-ori5aes-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5aes-main
.PHONY : nccsign-ori5aes-main

# fast build rule for target.
nccsign-ori5aes-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/test/CMakeFiles/nccsign-ori5aes-main.dir/build.make crypto_sign/NCCSign5-ori/test/CMakeFiles/nccsign-ori5aes-main.dir/build
.PHONY : nccsign-ori5aes-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori5-kat-sign

# Build rule for target.
nccsign-ori5-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5-kat-sign
.PHONY : nccsign-ori5-kat-sign

# fast build rule for target.
nccsign-ori5-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/kat/CMakeFiles/nccsign-ori5-kat-sign.dir/build.make crypto_sign/NCCSign5-ori/kat/CMakeFiles/nccsign-ori5-kat-sign.dir/build
.PHONY : nccsign-ori5-kat-sign/fast

#=============================================================================
# Target rules for targets named nccsign-ori5-kat-sign-main

# Build rule for target.
nccsign-ori5-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5-kat-sign-main
.PHONY : nccsign-ori5-kat-sign-main

# fast build rule for target.
nccsign-ori5-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/kat/CMakeFiles/nccsign-ori5-kat-sign-main.dir/build.make crypto_sign/NCCSign5-ori/kat/CMakeFiles/nccsign-ori5-kat-sign-main.dir/build
.PHONY : nccsign-ori5-kat-sign-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori5aes-kat-sign

# Build rule for target.
nccsign-ori5aes-kat-sign: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5aes-kat-sign
.PHONY : nccsign-ori5aes-kat-sign

# fast build rule for target.
nccsign-ori5aes-kat-sign/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/kat/CMakeFiles/nccsign-ori5aes-kat-sign.dir/build.make crypto_sign/NCCSign5-ori/kat/CMakeFiles/nccsign-ori5aes-kat-sign.dir/build
.PHONY : nccsign-ori5aes-kat-sign/fast

#=============================================================================
# Target rules for targets named nccsign-ori5aes-kat-sign-main

# Build rule for target.
nccsign-ori5aes-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5aes-kat-sign-main
.PHONY : nccsign-ori5aes-kat-sign-main

# fast build rule for target.
nccsign-ori5aes-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/kat/CMakeFiles/nccsign-ori5aes-kat-sign-main.dir/build.make crypto_sign/NCCSign5-ori/kat/CMakeFiles/nccsign-ori5aes-kat-sign-main.dir/build
.PHONY : nccsign-ori5aes-kat-sign-main/fast

#=============================================================================
# Target rules for targets named nccsign-ori5-benchmark

# Build rule for target.
nccsign-ori5-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5-benchmark
.PHONY : nccsign-ori5-benchmark

# fast build rule for target.
nccsign-ori5-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/benchmark/CMakeFiles/nccsign-ori5-benchmark.dir/build.make crypto_sign/NCCSign5-ori/benchmark/CMakeFiles/nccsign-ori5-benchmark.dir/build
.PHONY : nccsign-ori5-benchmark/fast

#=============================================================================
# Target rules for targets named nccsign-ori5aes-benchmark

# Build rule for target.
nccsign-ori5aes-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nccsign-ori5aes-benchmark
.PHONY : nccsign-ori5aes-benchmark

# fast build rule for target.
nccsign-ori5aes-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/NCCSign5-ori/benchmark/CMakeFiles/nccsign-ori5aes-benchmark.dir/build.make crypto_sign/NCCSign5-ori/benchmark/CMakeFiles/nccsign-ori5aes-benchmark.dir/build
.PHONY : nccsign-ori5aes-benchmark/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... common"
	@echo "... haetae2"
	@echo "... haetae2-benchmark"
	@echo "... haetae2-kat-sign"
	@echo "... haetae2-kat-sign-main"
	@echo "... haetae2-main"
	@echo "... haetae2-meta"
	@echo "... haetae2-meta-main"
	@echo "... haetae2_RNG"
	@echo "... haetae2_fips202"
	@echo "... haetae3"
	@echo "... haetae3-benchmark"
	@echo "... haetae3-kat-sign"
	@echo "... haetae3-kat-sign-main"
	@echo "... haetae3-main"
	@echo "... haetae3-meta"
	@echo "... haetae3-meta-main"
	@echo "... haetae3_RNG"
	@echo "... haetae3_fips202"
	@echo "... haetae5"
	@echo "... haetae5-benchmark"
	@echo "... haetae5-kat-sign"
	@echo "... haetae5-kat-sign-main"
	@echo "... haetae5-main"
	@echo "... haetae5-meta"
	@echo "... haetae5-meta-main"
	@echo "... haetae5_RNG"
	@echo "... haetae5_fips202"
	@echo "... nccsign-ori2"
	@echo "... nccsign-ori2-benchmark"
	@echo "... nccsign-ori2-kat-sign"
	@echo "... nccsign-ori2-kat-sign-main"
	@echo "... nccsign-ori2-main"
	@echo "... nccsign-ori2aes"
	@echo "... nccsign-ori2aes-benchmark"
	@echo "... nccsign-ori2aes-kat-sign"
	@echo "... nccsign-ori2aes-kat-sign-main"
	@echo "... nccsign-ori2aes-main"
	@echo "... nccsign-ori3"
	@echo "... nccsign-ori3-benchmark"
	@echo "... nccsign-ori3-kat-sign"
	@echo "... nccsign-ori3-kat-sign-main"
	@echo "... nccsign-ori3-main"
	@echo "... nccsign-ori3aes"
	@echo "... nccsign-ori3aes-benchmark"
	@echo "... nccsign-ori3aes-kat-sign"
	@echo "... nccsign-ori3aes-kat-sign-main"
	@echo "... nccsign-ori3aes-main"
	@echo "... nccsign-ori5"
	@echo "... nccsign-ori5-benchmark"
	@echo "... nccsign-ori5-kat-sign"
	@echo "... nccsign-ori5-kat-sign-main"
	@echo "... nccsign-ori5-main"
	@echo "... nccsign-ori5aes"
	@echo "... nccsign-ori5aes-benchmark"
	@echo "... nccsign-ori5aes-kat-sign"
	@echo "... nccsign-ori5aes-kat-sign-main"
	@echo "... nccsign-ori5aes-main"
	@echo "... nccsign2_aes256ctr"
	@echo "... nccsign2_fips202"
	@echo "... nccsign3_aes256ctr"
	@echo "... nccsign3_fips202"
	@echo "... nccsign5_aes256ctr"
	@echo "... nccsign5_fips202"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

