# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/unlimit/Downloads/KPQClean

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/unlimit/Downloads/KPQClean

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unlimit/Downloads/KPQClean/CMakeFiles /home/unlimit/Downloads/KPQClean//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unlimit/Downloads/KPQClean/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f common/CMakeFiles/common.dir/build.make common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named Peregrine512_RNG

# Build rule for target.
Peregrine512_RNG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine512_RNG
.PHONY : Peregrine512_RNG

# fast build rule for target.
Peregrine512_RNG/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine512/CMakeFiles/Peregrine512_RNG.dir/build.make crypto_sign/Peregrine512/CMakeFiles/Peregrine512_RNG.dir/build
.PHONY : Peregrine512_RNG/fast

#=============================================================================
# Target rules for targets named Peregrine512

# Build rule for target.
Peregrine512: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine512
.PHONY : Peregrine512

# fast build rule for target.
Peregrine512/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine512/CMakeFiles/Peregrine512.dir/build.make crypto_sign/Peregrine512/CMakeFiles/Peregrine512.dir/build
.PHONY : Peregrine512/fast

#=============================================================================
# Target rules for targets named Peregrine512-main

# Build rule for target.
Peregrine512-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine512-main
.PHONY : Peregrine512-main

# fast build rule for target.
Peregrine512-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine512/test/CMakeFiles/Peregrine512-main.dir/build.make crypto_sign/Peregrine512/test/CMakeFiles/Peregrine512-main.dir/build
.PHONY : Peregrine512-main/fast

#=============================================================================
# Target rules for targets named Peregrine512-kat-sign-main

# Build rule for target.
Peregrine512-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine512-kat-sign-main
.PHONY : Peregrine512-kat-sign-main

# fast build rule for target.
Peregrine512-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine512/kat/CMakeFiles/Peregrine512-kat-sign-main.dir/build.make crypto_sign/Peregrine512/kat/CMakeFiles/Peregrine512-kat-sign-main.dir/build
.PHONY : Peregrine512-kat-sign-main/fast

#=============================================================================
# Target rules for targets named Peregrine512-benchmark

# Build rule for target.
Peregrine512-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine512-benchmark
.PHONY : Peregrine512-benchmark

# fast build rule for target.
Peregrine512-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine512/benchmark/CMakeFiles/Peregrine512-benchmark.dir/build.make crypto_sign/Peregrine512/benchmark/CMakeFiles/Peregrine512-benchmark.dir/build
.PHONY : Peregrine512-benchmark/fast

#=============================================================================
# Target rules for targets named Peregrine512-const-test-main

# Build rule for target.
Peregrine512-const-test-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine512-const-test-main
.PHONY : Peregrine512-const-test-main

# fast build rule for target.
Peregrine512-const-test-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine512/const_test/CMakeFiles/Peregrine512-const-test-main.dir/build.make crypto_sign/Peregrine512/const_test/CMakeFiles/Peregrine512-const-test-main.dir/build
.PHONY : Peregrine512-const-test-main/fast

#=============================================================================
# Target rules for targets named Peregrine1024_RNG

# Build rule for target.
Peregrine1024_RNG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine1024_RNG
.PHONY : Peregrine1024_RNG

# fast build rule for target.
Peregrine1024_RNG/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine1024/CMakeFiles/Peregrine1024_RNG.dir/build.make crypto_sign/Peregrine1024/CMakeFiles/Peregrine1024_RNG.dir/build
.PHONY : Peregrine1024_RNG/fast

#=============================================================================
# Target rules for targets named Peregrine1024

# Build rule for target.
Peregrine1024: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine1024
.PHONY : Peregrine1024

# fast build rule for target.
Peregrine1024/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine1024/CMakeFiles/Peregrine1024.dir/build.make crypto_sign/Peregrine1024/CMakeFiles/Peregrine1024.dir/build
.PHONY : Peregrine1024/fast

#=============================================================================
# Target rules for targets named Peregrine1024-main

# Build rule for target.
Peregrine1024-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine1024-main
.PHONY : Peregrine1024-main

# fast build rule for target.
Peregrine1024-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine1024/test/CMakeFiles/Peregrine1024-main.dir/build.make crypto_sign/Peregrine1024/test/CMakeFiles/Peregrine1024-main.dir/build
.PHONY : Peregrine1024-main/fast

#=============================================================================
# Target rules for targets named Peregrine1024-kat-sign-main

# Build rule for target.
Peregrine1024-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine1024-kat-sign-main
.PHONY : Peregrine1024-kat-sign-main

# fast build rule for target.
Peregrine1024-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine1024/kat/CMakeFiles/Peregrine1024-kat-sign-main.dir/build.make crypto_sign/Peregrine1024/kat/CMakeFiles/Peregrine1024-kat-sign-main.dir/build
.PHONY : Peregrine1024-kat-sign-main/fast

#=============================================================================
# Target rules for targets named Peregrine1024-benchmark

# Build rule for target.
Peregrine1024-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine1024-benchmark
.PHONY : Peregrine1024-benchmark

# fast build rule for target.
Peregrine1024-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine1024/benchmark/CMakeFiles/Peregrine1024-benchmark.dir/build.make crypto_sign/Peregrine1024/benchmark/CMakeFiles/Peregrine1024-benchmark.dir/build
.PHONY : Peregrine1024-benchmark/fast

#=============================================================================
# Target rules for targets named Peregrine1024-const-test-main

# Build rule for target.
Peregrine1024-const-test-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Peregrine1024-const-test-main
.PHONY : Peregrine1024-const-test-main

# fast build rule for target.
Peregrine1024-const-test-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/Peregrine1024/const_test/CMakeFiles/Peregrine1024-const-test-main.dir/build.make crypto_sign/Peregrine1024/const_test/CMakeFiles/Peregrine1024-const-test-main.dir/build
.PHONY : Peregrine1024-const-test-main/fast

#=============================================================================
# Target rules for targets named MQS256-72-46_RNG

# Build rule for target.
MQS256-72-46_RNG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-72-46_RNG
.PHONY : MQS256-72-46_RNG

# fast build rule for target.
MQS256-72-46_RNG/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-72-46/CMakeFiles/MQS256-72-46_RNG.dir/build.make crypto_sign/MQS256-72-46/CMakeFiles/MQS256-72-46_RNG.dir/build
.PHONY : MQS256-72-46_RNG/fast

#=============================================================================
# Target rules for targets named MQS256-72-46

# Build rule for target.
MQS256-72-46: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-72-46
.PHONY : MQS256-72-46

# fast build rule for target.
MQS256-72-46/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-72-46/CMakeFiles/MQS256-72-46.dir/build.make crypto_sign/MQS256-72-46/CMakeFiles/MQS256-72-46.dir/build
.PHONY : MQS256-72-46/fast

#=============================================================================
# Target rules for targets named MQS256-72-46-main

# Build rule for target.
MQS256-72-46-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-72-46-main
.PHONY : MQS256-72-46-main

# fast build rule for target.
MQS256-72-46-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-72-46/test/CMakeFiles/MQS256-72-46-main.dir/build.make crypto_sign/MQS256-72-46/test/CMakeFiles/MQS256-72-46-main.dir/build
.PHONY : MQS256-72-46-main/fast

#=============================================================================
# Target rules for targets named MQS256-72-46-kat-sign-main

# Build rule for target.
MQS256-72-46-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-72-46-kat-sign-main
.PHONY : MQS256-72-46-kat-sign-main

# fast build rule for target.
MQS256-72-46-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-72-46/kat/CMakeFiles/MQS256-72-46-kat-sign-main.dir/build.make crypto_sign/MQS256-72-46/kat/CMakeFiles/MQS256-72-46-kat-sign-main.dir/build
.PHONY : MQS256-72-46-kat-sign-main/fast

#=============================================================================
# Target rules for targets named MQS256-72-46-benchmark

# Build rule for target.
MQS256-72-46-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-72-46-benchmark
.PHONY : MQS256-72-46-benchmark

# fast build rule for target.
MQS256-72-46-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-72-46/benchmark/CMakeFiles/MQS256-72-46-benchmark.dir/build.make crypto_sign/MQS256-72-46/benchmark/CMakeFiles/MQS256-72-46-benchmark.dir/build
.PHONY : MQS256-72-46-benchmark/fast

#=============================================================================
# Target rules for targets named MQS256-72-46-meta

# Build rule for target.
MQS256-72-46-meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-72-46-meta
.PHONY : MQS256-72-46-meta

# fast build rule for target.
MQS256-72-46-meta/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-72-46/metamorphic/CMakeFiles/MQS256-72-46-meta.dir/build.make crypto_sign/MQS256-72-46/metamorphic/CMakeFiles/MQS256-72-46-meta.dir/build
.PHONY : MQS256-72-46-meta/fast

#=============================================================================
# Target rules for targets named MQS256-72-46-meta-main

# Build rule for target.
MQS256-72-46-meta-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-72-46-meta-main
.PHONY : MQS256-72-46-meta-main

# fast build rule for target.
MQS256-72-46-meta-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-72-46/metamorphic/CMakeFiles/MQS256-72-46-meta-main.dir/build.make crypto_sign/MQS256-72-46/metamorphic/CMakeFiles/MQS256-72-46-meta-main.dir/build
.PHONY : MQS256-72-46-meta-main/fast

#=============================================================================
# Target rules for targets named MQS256-72-46-const-test-main

# Build rule for target.
MQS256-72-46-const-test-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-72-46-const-test-main
.PHONY : MQS256-72-46-const-test-main

# fast build rule for target.
MQS256-72-46-const-test-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-72-46/const_test/CMakeFiles/MQS256-72-46-const-test-main.dir/build.make crypto_sign/MQS256-72-46/const_test/CMakeFiles/MQS256-72-46-const-test-main.dir/build
.PHONY : MQS256-72-46-const-test-main/fast

#=============================================================================
# Target rules for targets named MQS256-148-96_RNG

# Build rule for target.
MQS256-148-96_RNG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-148-96_RNG
.PHONY : MQS256-148-96_RNG

# fast build rule for target.
MQS256-148-96_RNG/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-148-96/CMakeFiles/MQS256-148-96_RNG.dir/build.make crypto_sign/MQS256-148-96/CMakeFiles/MQS256-148-96_RNG.dir/build
.PHONY : MQS256-148-96_RNG/fast

#=============================================================================
# Target rules for targets named MQS256-148-96

# Build rule for target.
MQS256-148-96: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-148-96
.PHONY : MQS256-148-96

# fast build rule for target.
MQS256-148-96/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-148-96/CMakeFiles/MQS256-148-96.dir/build.make crypto_sign/MQS256-148-96/CMakeFiles/MQS256-148-96.dir/build
.PHONY : MQS256-148-96/fast

#=============================================================================
# Target rules for targets named MQS256-148-96-main

# Build rule for target.
MQS256-148-96-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-148-96-main
.PHONY : MQS256-148-96-main

# fast build rule for target.
MQS256-148-96-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-148-96/test/CMakeFiles/MQS256-148-96-main.dir/build.make crypto_sign/MQS256-148-96/test/CMakeFiles/MQS256-148-96-main.dir/build
.PHONY : MQS256-148-96-main/fast

#=============================================================================
# Target rules for targets named MQS256-148-96-kat-sign-main

# Build rule for target.
MQS256-148-96-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-148-96-kat-sign-main
.PHONY : MQS256-148-96-kat-sign-main

# fast build rule for target.
MQS256-148-96-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-148-96/kat/CMakeFiles/MQS256-148-96-kat-sign-main.dir/build.make crypto_sign/MQS256-148-96/kat/CMakeFiles/MQS256-148-96-kat-sign-main.dir/build
.PHONY : MQS256-148-96-kat-sign-main/fast

#=============================================================================
# Target rules for targets named MQS256-148-96-benchmark

# Build rule for target.
MQS256-148-96-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-148-96-benchmark
.PHONY : MQS256-148-96-benchmark

# fast build rule for target.
MQS256-148-96-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-148-96/benchmark/CMakeFiles/MQS256-148-96-benchmark.dir/build.make crypto_sign/MQS256-148-96/benchmark/CMakeFiles/MQS256-148-96-benchmark.dir/build
.PHONY : MQS256-148-96-benchmark/fast

#=============================================================================
# Target rules for targets named MQS256-148-96-meta

# Build rule for target.
MQS256-148-96-meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-148-96-meta
.PHONY : MQS256-148-96-meta

# fast build rule for target.
MQS256-148-96-meta/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-148-96/metamorphic/CMakeFiles/MQS256-148-96-meta.dir/build.make crypto_sign/MQS256-148-96/metamorphic/CMakeFiles/MQS256-148-96-meta.dir/build
.PHONY : MQS256-148-96-meta/fast

#=============================================================================
# Target rules for targets named MQS256-148-96-meta-main

# Build rule for target.
MQS256-148-96-meta-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-148-96-meta-main
.PHONY : MQS256-148-96-meta-main

# fast build rule for target.
MQS256-148-96-meta-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-148-96/metamorphic/CMakeFiles/MQS256-148-96-meta-main.dir/build.make crypto_sign/MQS256-148-96/metamorphic/CMakeFiles/MQS256-148-96-meta-main.dir/build
.PHONY : MQS256-148-96-meta-main/fast

#=============================================================================
# Target rules for targets named MQS256-148-96-const-test-main

# Build rule for target.
MQS256-148-96-const-test-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-148-96-const-test-main
.PHONY : MQS256-148-96-const-test-main

# fast build rule for target.
MQS256-148-96-const-test-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-148-96/const_test/CMakeFiles/MQS256-148-96-const-test-main.dir/build.make crypto_sign/MQS256-148-96/const_test/CMakeFiles/MQS256-148-96-const-test-main.dir/build
.PHONY : MQS256-148-96-const-test-main/fast

#=============================================================================
# Target rules for targets named MQS256-112-72_RNG

# Build rule for target.
MQS256-112-72_RNG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-112-72_RNG
.PHONY : MQS256-112-72_RNG

# fast build rule for target.
MQS256-112-72_RNG/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-112-72/CMakeFiles/MQS256-112-72_RNG.dir/build.make crypto_sign/MQS256-112-72/CMakeFiles/MQS256-112-72_RNG.dir/build
.PHONY : MQS256-112-72_RNG/fast

#=============================================================================
# Target rules for targets named MQS256-112-72

# Build rule for target.
MQS256-112-72: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-112-72
.PHONY : MQS256-112-72

# fast build rule for target.
MQS256-112-72/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-112-72/CMakeFiles/MQS256-112-72.dir/build.make crypto_sign/MQS256-112-72/CMakeFiles/MQS256-112-72.dir/build
.PHONY : MQS256-112-72/fast

#=============================================================================
# Target rules for targets named MQS256-112-72-main

# Build rule for target.
MQS256-112-72-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-112-72-main
.PHONY : MQS256-112-72-main

# fast build rule for target.
MQS256-112-72-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-112-72/test/CMakeFiles/MQS256-112-72-main.dir/build.make crypto_sign/MQS256-112-72/test/CMakeFiles/MQS256-112-72-main.dir/build
.PHONY : MQS256-112-72-main/fast

#=============================================================================
# Target rules for targets named MQS256-112-72-kat-sign-main

# Build rule for target.
MQS256-112-72-kat-sign-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-112-72-kat-sign-main
.PHONY : MQS256-112-72-kat-sign-main

# fast build rule for target.
MQS256-112-72-kat-sign-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-112-72/kat/CMakeFiles/MQS256-112-72-kat-sign-main.dir/build.make crypto_sign/MQS256-112-72/kat/CMakeFiles/MQS256-112-72-kat-sign-main.dir/build
.PHONY : MQS256-112-72-kat-sign-main/fast

#=============================================================================
# Target rules for targets named MQS256-112-72-benchmark

# Build rule for target.
MQS256-112-72-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-112-72-benchmark
.PHONY : MQS256-112-72-benchmark

# fast build rule for target.
MQS256-112-72-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-112-72/benchmark/CMakeFiles/MQS256-112-72-benchmark.dir/build.make crypto_sign/MQS256-112-72/benchmark/CMakeFiles/MQS256-112-72-benchmark.dir/build
.PHONY : MQS256-112-72-benchmark/fast

#=============================================================================
# Target rules for targets named MQS256-112-72-meta

# Build rule for target.
MQS256-112-72-meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-112-72-meta
.PHONY : MQS256-112-72-meta

# fast build rule for target.
MQS256-112-72-meta/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-112-72/metamorphic/CMakeFiles/MQS256-112-72-meta.dir/build.make crypto_sign/MQS256-112-72/metamorphic/CMakeFiles/MQS256-112-72-meta.dir/build
.PHONY : MQS256-112-72-meta/fast

#=============================================================================
# Target rules for targets named MQS256-112-72-meta-main

# Build rule for target.
MQS256-112-72-meta-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-112-72-meta-main
.PHONY : MQS256-112-72-meta-main

# fast build rule for target.
MQS256-112-72-meta-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-112-72/metamorphic/CMakeFiles/MQS256-112-72-meta-main.dir/build.make crypto_sign/MQS256-112-72/metamorphic/CMakeFiles/MQS256-112-72-meta-main.dir/build
.PHONY : MQS256-112-72-meta-main/fast

#=============================================================================
# Target rules for targets named MQS256-112-72-const-test-main

# Build rule for target.
MQS256-112-72-const-test-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MQS256-112-72-const-test-main
.PHONY : MQS256-112-72-const-test-main

# fast build rule for target.
MQS256-112-72-const-test-main/fast:
	$(MAKE) $(MAKESILENT) -f crypto_sign/MQS256-112-72/const_test/CMakeFiles/MQS256-112-72-const-test-main.dir/build.make crypto_sign/MQS256-112-72/const_test/CMakeFiles/MQS256-112-72-const-test-main.dir/build
.PHONY : MQS256-112-72-const-test-main/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MQS256-112-72"
	@echo "... MQS256-112-72-benchmark"
	@echo "... MQS256-112-72-const-test-main"
	@echo "... MQS256-112-72-kat-sign-main"
	@echo "... MQS256-112-72-main"
	@echo "... MQS256-112-72-meta"
	@echo "... MQS256-112-72-meta-main"
	@echo "... MQS256-112-72_RNG"
	@echo "... MQS256-148-96"
	@echo "... MQS256-148-96-benchmark"
	@echo "... MQS256-148-96-const-test-main"
	@echo "... MQS256-148-96-kat-sign-main"
	@echo "... MQS256-148-96-main"
	@echo "... MQS256-148-96-meta"
	@echo "... MQS256-148-96-meta-main"
	@echo "... MQS256-148-96_RNG"
	@echo "... MQS256-72-46"
	@echo "... MQS256-72-46-benchmark"
	@echo "... MQS256-72-46-const-test-main"
	@echo "... MQS256-72-46-kat-sign-main"
	@echo "... MQS256-72-46-main"
	@echo "... MQS256-72-46-meta"
	@echo "... MQS256-72-46-meta-main"
	@echo "... MQS256-72-46_RNG"
	@echo "... Peregrine1024"
	@echo "... Peregrine1024-benchmark"
	@echo "... Peregrine1024-const-test-main"
	@echo "... Peregrine1024-kat-sign-main"
	@echo "... Peregrine1024-main"
	@echo "... Peregrine1024_RNG"
	@echo "... Peregrine512"
	@echo "... Peregrine512-benchmark"
	@echo "... Peregrine512-const-test-main"
	@echo "... Peregrine512-kat-sign-main"
	@echo "... Peregrine512-main"
	@echo "... Peregrine512_RNG"
	@echo "... common"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

