CC		= gcc
LDFLAGS=-lcrypto
LDFLAGS+="-L/usr/local/opt/openssl@3/lib"
CPPFLAGS="-I/usr/local/opt/openssl@3/include"

SOURCES= PQCgenKAT_pke.c pke.c Keygen.c Encryption.c MultiEnc.c Decryption.c rng.c verify.c fips202.c
HEADERS= api.h Keygen.h Encryption.h MultiEnc.h Decryption.h params.h rng.h verify.h fips202.h


PQCgenKAT_pke: $(HEADERS) $(SOURCES)
	$(CC) -o $@ $(SOURCES) $(LDFLAGS) $(CPPFLAGS)

clean:
	@rm -rf *.o PQCgenKAT_pke
